"use client";

import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowDown, ArrowUpRight, CalendarDays, ChevronDown, Instagram, Mail, MapPin, Menu, Minus, Phone, Plus, Star, Waves, X } from "lucide-react";

const IMG={
 hero:"https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=2200&q=90",
 pool:"https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1600&q=88",
 room:"https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1400&q=88",
 room2:"https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1400&q=88",
 dining:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=88",
 spa:"https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1400&q=88",
 beach:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=88",
 sunset:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1600&q=88",
 breakfast:"https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=1200&q=88",
};

const rooms=[
 {name:"Superior Mountain View",meta:"22 m² · 2 guests · Queen / Twin",price:"From 780,000 VND",img:IMG.room,copy:"Quiet, airy and considered — a comfortable base for island days."},
 {name:"Deluxe Triple Room",meta:"25 m² · 3 guests · Three twins",price:"From 980,000 VND",img:IMG.room2,copy:"More space for friends and small families, with generous daylight."},
 {name:"Family Room",meta:"30 m² · 4 guests · Two doubles",price:"From 1,180,000 VND",img:IMG.hero,copy:"A relaxed family retreat with room to slow down after the beach."},
];

const gallery=[IMG.pool,IMG.room,IMG.beach,IMG.dining,IMG.sunset,IMG.spa];

export default function Home(){
 const [open,setOpen]=useState(false); const [menu,setMenu]=useState(false); const [roomsOpen,setRoomsOpen]=useState(0);
 useEffect(()=>{let l:any; import("@studio-freight/lenis").then(({default:Lenis})=>{l=new Lenis({duration:1.2,smoothWheel:true,wheelMultiplier:.8,touchMultiplier:1}); const raf=(t:number)=>{l.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf)});return()=>l?.destroy()},[]);
 const go=(id:string)=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};
 return <main>
  <header className="fixed left-0 right-0 top-0 z-50 border-b border-white/15 bg-ink/15 text-white backdrop-blur-md">
   <div className="container flex h-[82px] items-center justify-between">
    <button onClick={()=>go("home")} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full border border-gold/70 text-gold"><span className="serif text-xl">G</span></span><span className="text-left leading-none"><b className="block text-[15px] tracking-[.18em]">GOLDEN DAISY</b><small className="mt-1 block text-[9px] tracking-[.32em] text-white/65">HOTEL · PHU QUOC</small></span></button>
    <nav className="hidden items-center gap-8 text-[11px] uppercase tracking-[.18em] lg:flex"><button onClick={()=>go("stay")}>Stay</button><button onClick={()=>go("experience")}>Experience</button><button onClick={()=>go("dining")}>Dining</button><button onClick={()=>go("gallery")}>Gallery</button><button onClick={()=>go("location")}>Location</button></nav>
    <div className="flex items-center gap-3"><button onClick={()=>setOpen(true)} className="hidden border border-gold bg-gold px-5 py-3 text-[10px] font-semibold uppercase tracking-[.2em] text-ink transition hover:bg-transparent hover:text-white sm:block">Book your stay</button><button className="lg:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>
   </div>
   <AnimatePresence>{menu&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden bg-ink p-6 lg:hidden"><div className="grid gap-5 text-sm uppercase tracking-[.16em]"><button onClick={()=>go("stay")}>Stay</button><button onClick={()=>go("experience")}>Experience</button><button onClick={()=>go("dining")}>Dining</button><button onClick={()=>go("gallery")}>Gallery</button><button onClick={()=>go("location")}>Location</button><button onClick={()=>setOpen(true)} className="bg-gold py-4 text-ink">Book your stay</button></div></motion.div>}</AnimatePresence>
  </header>

  <section id="home" className="relative flex min-h-[92vh] items-end overflow-hidden bg-ink text-white">
   <img src={IMG.hero} className="absolute inset-0 h-full w-full object-cover" alt="Golden Daisy Hotel Phu Quoc"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/35 to-black/10"/>
   <div className="container relative z-10 pb-28 pt-40"><div className="max-w-4xl"><p className="eyebrow mb-6 text-gold">A tropical pause · Phu Quoc Island</p><h1 className="serif max-w-4xl text-6xl leading-[.98] tracking-[-.04em] sm:text-7xl lg:text-[112px]">Stay close to<br/><i className="font-normal text-gold">the island.</i></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/75 sm:text-lg">A warm, contemporary hotel in the heart of Phu Quoc — made for slow mornings, golden afternoons and easy island adventures.</p></div><div className="mt-12 flex items-center gap-8 text-xs uppercase tracking-[.2em] text-white/60"><span className="flex items-center gap-2"><MapPin size={14}/> Tran Hung Dao</span><span className="hidden h-px w-20 bg-white/30 sm:block"/><span>Long Beach · &lt; 1 km</span></div></div>
   <button onClick={()=>go("stay")} className="absolute bottom-8 right-8 hidden items-center gap-3 text-[10px] uppercase tracking-[.25em] md:flex">Scroll to explore <span className="grid h-10 w-10 place-items-center rounded-full border border-white/40"><ArrowDown size={15}/></span></button>
  </section>

  <BookingBar onBook={()=>setOpen(true)}/>

  <section className="section bg-paper"><div className="container grid items-center gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Golden Daisy Hotel</p><h2 className="serif mt-5 text-5xl leading-[1.03] tracking-[-.03em] sm:text-6xl">A little more<br/><i className="font-normal text-gold">island,</i> a lot more ease.</h2></div><div className="max-w-xl"><p className="text-xl leading-8 text-ink/80">Set on Tran Hung Dao in central Phu Quoc, Golden Daisy gives you an effortless starting point for the island — with a rooftop pool, restaurant, wellness spaces and a friendly 24-hour team.</p><div className="mt-10 grid grid-cols-3 gap-4 border-t border-ink/15 pt-7 text-sm"><Stat value="8.5/10" label="Guest rating"/><Stat value="9.0/10" label="Location"/><Stat value="9.2/10" label="Free Wi-Fi"/></div></div></div></section>

  <section id="stay" className="section bg-cream"><div className="container"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow">The rooms</p><h2 className="serif mt-4 text-5xl tracking-[-.03em] sm:text-7xl">Sleep beautifully.</h2></div><p className="max-w-md text-sm leading-6 text-ink/65">Natural light, comfortable beds and the practical details you need after a full day exploring the island.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{rooms.map((r,i)=><motion.article initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} key={r.name} className="group bg-paper"><div className="image-wrap aspect-[4/3]"><img src={r.img} alt={r.name}/><span className="absolute"/></div><div className="p-7"><div className="flex items-start justify-between gap-4"><h3 className="serif text-2xl">{r.name}</h3><span className="text-gold"><ArrowUpRight size={20}/></span></div><p className="mt-3 text-xs uppercase tracking-[.13em] text-ink/50">{r.meta}</p><p className="mt-5 text-sm leading-6 text-ink/65">{r.copy}</p><div className="mt-7 flex items-center justify-between border-t border-ink/10 pt-5"><span className="text-sm font-semibold">{r.price}</span><button onClick={()=>setOpen(true)} className="text-[10px] uppercase tracking-[.18em] underline underline-offset-4">Check dates</button></div></div></motion.article>)}</div></div></section>

  <section id="experience" className="section bg-ink text-white"><div className="container grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div className="image-wrap aspect-[4/5]"><img src={IMG.pool} alt="Rooftop pool"/></div><div className="lg:pl-10"><p className="eyebrow">Rooftop ritual</p><h2 className="serif mt-5 text-5xl leading-[1.03] sm:text-7xl">Golden hour<br/><i className="font-normal text-gold">starts upstairs.</i></h2><p className="mt-7 max-w-md leading-7 text-white/65">Swim above the city, settle into a lounger and watch Phu Quoc change colour as the sun drops toward the sea.</p><div className="mt-10 grid grid-cols-2 gap-5 border-t border-white/15 pt-6 text-sm"><div><Waves size={18} className="mb-3 text-gold"/><b>Rooftop pool</b><p className="mt-1 text-white/50">Views over the island</p></div><div><Star size={18} className="mb-3 text-gold"/><b>Sunset views</b><p className="mt-1 text-white/50">An easy evening ritual</p></div></div></div></div></section>

  <section id="dining" className="section"><div className="container grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="lg:pt-10"><p className="eyebrow">Taste of the island</p><h2 className="serif mt-4 text-5xl leading-[1.04] sm:text-7xl">Good food.<br/><i className="font-normal text-gold">No rush.</i></h2><p className="mt-7 max-w-md leading-7 text-ink/65">Start with breakfast, return for a relaxed meal and leave room for one more drink. Our dining spaces are designed for easy, unhurried moments.</p><div className="mt-9 space-y-5 border-t border-ink/10 pt-6 text-sm"><p className="flex justify-between"><span>Breakfast</span><span className="text-ink/50">06:30 — 09:30</span></p><p className="flex justify-between"><span>Restaurant</span><span className="text-ink/50">Daily service</span></p><p className="flex justify-between"><span>Rooftop</span><span className="text-ink/50">Sunset onwards</span></p></div></div><div className="grid gap-5 sm:grid-cols-2"><div className="image-wrap aspect-[3/4] sm:mt-16"><img src={IMG.dining} alt="Dining at Golden Daisy"/></div><div className="image-wrap aspect-[3/4]"><img src={IMG.breakfast} alt="Breakfast"/></div></div></div></section>

  <section className="section bg-cream"><div className="container grid items-center gap-10 lg:grid-cols-2"><div className="image-wrap aspect-[16/11]"><img src={IMG.spa} alt="Wellness"/></div><div className="lg:pl-10"><p className="eyebrow">Wellness & care</p><h2 className="serif mt-4 text-5xl leading-tight sm:text-6xl">Make space<br/>for yourself.</h2><p className="mt-6 max-w-lg leading-7 text-ink/65">From a quiet massage to a quick workout before breakfast, the hotel gives you simple ways to keep your holiday feeling balanced.</p><div className="mt-8 grid grid-cols-2 gap-3">{["Spa & massage","Fitness centre","Airport shuttle","24-hour front desk"].map(x=><div key={x} className="border border-ink/10 bg-paper p-5 text-sm">{x}</div>)}</div></div></div></section>

  <section id="gallery" className="section"><div className="container"><div className="flex items-end justify-between"><div><p className="eyebrow">A glimpse</p><h2 className="serif mt-4 text-5xl sm:text-7xl">Island days.</h2></div><Instagram className="hidden text-gold sm:block"/></div><div className="mt-12 grid grid-cols-2 gap-3 md:grid-cols-3">{gallery.map((x,i)=><div key={x} className={`image-wrap ${i===0||i===3?'aspect-[4/5]':'aspect-square'}`}><img src={x} alt="Golden Daisy Hotel gallery"/></div>)}</div></div></section>

  <section className="relative overflow-hidden bg-gold text-ink"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(255,255,255,.28),transparent_32%)]"/><div className="container relative py-24 text-center"><p className="eyebrow !text-ink/60">Your Phu Quoc chapter</p><h2 className="serif mx-auto mt-5 max-w-3xl text-5xl leading-none sm:text-7xl">Come for the island.<br/><i>Stay for the feeling.</i></h2><button onClick={()=>setOpen(true)} className="mt-9 inline-flex items-center gap-3 bg-ink px-7 py-4 text-xs uppercase tracking-[.2em] text-white transition hover:bg-white hover:text-ink">Book your stay <ArrowUpRight size={16}/></button></div></section>

  <section id="location" className="section bg-paper"><div className="container grid gap-12 lg:grid-cols-[1fr_1.1fr]"><div><p className="eyebrow">Find us</p><h2 className="serif mt-4 text-5xl sm:text-6xl">Central,<br/><i className="font-normal text-gold">yet unhurried.</i></h2><p className="mt-6 max-w-md leading-7 text-ink/65">127 Tran Hung Dao, Khu Pho 7, Duong Dong, Phu Quoc. Long Beach is less than 1 km away and Phu Quoc International Airport is around 3 km away.</p><div className="mt-8 space-y-4 text-sm"><p className="flex gap-3"><MapPin className="shrink-0 text-gold" size={18}/>127 Tran Hung Dao, Phu Quoc, Vietnam</p><p className="flex gap-3"><Phone className="shrink-0 text-gold" size={18}/>+84 297 399 8222</p><p className="flex gap-3"><Mail className="shrink-0 text-gold" size={18}/>sales@goldendaisyhotel.vn</p></div></div><div className="min-h-[380px] overflow-hidden bg-[#d9ddd4]"><iframe title="Golden Daisy Hotel map" className="h-full min-h-[380px] w-full border-0 grayscale" src="https://www.google.com/maps?q=Golden%20Daisy%20Hotel%20Phu%20Quoc&output=embed" loading="lazy"/></div></div></section>

  <footer className="bg-ink py-14 text-white"><div className="container grid gap-10 md:grid-cols-3"><div><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full border border-gold text-gold"><span className="serif text-xl">G</span></span><div><b className="block tracking-[.18em]">GOLDEN DAISY</b><small className="text-[9px] tracking-[.3em] text-white/50">HOTEL · PHU QUOC</small></div></div><p className="mt-6 max-w-sm text-sm leading-6 text-white/50">A warm tropical stay in the heart of Phu Quoc.</p></div><div className="text-sm text-white/55"><p className="mb-4 text-[10px] uppercase tracking-[.2em] text-gold">Explore</p><div className="grid gap-3"><button className="text-left" onClick={()=>go("stay")}>Rooms</button><button className="text-left" onClick={()=>go("experience")}>Experience</button><button className="text-left" onClick={()=>go("gallery")}>Gallery</button></div></div><div className="text-sm text-white/55"><p className="mb-4 text-[10px] uppercase tracking-[.2em] text-gold">Contact</p><p>127 Tran Hung Dao, Phu Quoc</p><p className="mt-2">+84 297 399 8222</p><p className="mt-2">sales@goldendaisyhotel.vn</p></div></div><div className="container mt-12 border-t border-white/10 pt-6 text-[10px] uppercase tracking-[.18em] text-white/35">© {new Date().getFullYear()} Golden Daisy Hotel · Phu Quoc</div></footer>

  <AnimatePresence>{open&&<BookingModal close={()=>setOpen(false)} roomsOpen={roomsOpen} setRoomsOpen={setRoomsOpen}/>}</AnimatePresence>
 </main>
}

function Stat({value,label}:{value:string;label:string}){return <div><b className="block text-xl font-medium">{value}</b><span className="mt-1 block text-[10px] uppercase tracking-[.13em] text-ink/45">{label}</span></div>}
function BookingBar({onBook}:{onBook:()=>void}){return <div className="relative z-20 -mt-10"><div className="container"><div className="grid bg-paper p-3 shadow-2xl shadow-black/10 sm:grid-cols-4"><Field icon={<CalendarDays size={16}/>} label="Check in" value="Select date"/><Field icon={<CalendarDays size={16}/>} label="Check out" value="Select date"/><Field icon={<Star size={16}/>} label="Guests" value="2 adults · 1 room"/><button onClick={onBook} className="m-1 bg-ink px-5 py-5 text-xs uppercase tracking-[.18em] text-white transition hover:bg-gold hover:text-ink">Check availability</button></div></div></div>}
function Field({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="border-b border-ink/10 p-5 sm:border-b-0 sm:border-r"><div className="flex items-center gap-2 text-gold">{icon}<span className="text-[9px] uppercase tracking-[.18em]">{label}</span></div><p className="mt-2 text-sm">{value}</p></div>}
function BookingModal({close,roomsOpen,setRoomsOpen}:{close:()=>void;roomsOpen:number;setRoomsOpen:(n:number)=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[100] grid place-items-center bg-ink/70 p-4 backdrop-blur-sm"><motion.div initial={{y:25,opacity:0}} animate={{y:0,opacity:1}} className="relative max-h-[90vh] w-full max-w-2xl overflow-auto bg-paper p-7 sm:p-10"><button onClick={close} className="absolute right-6 top-6"><X/></button><p className="eyebrow">Golden Daisy Hotel</p><h2 className="serif mt-3 text-4xl">Plan your stay.</h2><p className="mt-3 text-sm text-ink/55">Choose your dates and room preferences. The button below opens the hotel booking channel.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><label className="border border-ink/15 p-4"><span className="block text-[9px] uppercase tracking-[.15em] text-gold">Check in</span><input type="date" className="mt-2 w-full bg-transparent outline-none"/></label><label className="border border-ink/15 p-4"><span className="block text-[9px] uppercase tracking-[.15em] text-gold">Check out</span><input type="date" className="mt-2 w-full bg-transparent outline-none"/></label></div><div className="mt-7 border-y border-ink/10 py-5"><button className="flex w-full items-center justify-between" onClick={()=>setRoomsOpen(roomsOpen?0:1)}><span><b className="block text-left text-sm">Guests & rooms</b><small className="text-ink/50">2 adults · 1 room</small></span>{roomsOpen?<Minus size={18}/>:<Plus size={18}/>}</button>{roomsOpen? <div className="mt-5 flex items-center justify-between bg-cream p-4"><span className="text-sm">Adults</span><div className="flex items-center gap-4"><button className="grid h-8 w-8 place-items-center rounded-full border border-ink/20"><Minus size={13}/></button><span>2</span><button className="grid h-8 w-8 place-items-center rounded-full border border-ink/20"><Plus size={13}/></button></div></div>:null}</div><a href="https://www.booking.com/hotel/vn/daisy-golden.en-gb.html" target="_blank" rel="noreferrer" className="mt-7 flex items-center justify-center gap-3 bg-ink py-4 text-xs uppercase tracking-[.2em] text-white hover:bg-gold hover:text-ink">Continue to booking <ArrowUpRight size={16}/></a><p className="mt-4 text-center text-[10px] text-ink/40">Rates and live availability are handled by the booking partner.</p></motion.div></motion.div>}
